"""
METHOD 2 -- Agreement / LLM-judge-guided self-training
======================================================

THE PROBLEM IT SOLVES
  Your labels are SILVER-STANDARD (generated by Whisper large-v3, not humans),
  so they contain errors. A model trained on noisy labels inherits a ceiling:
  part of the measured error is label noise, not model failure. This is the #1
  reviewer concern for the dataset.

THE FIX (the method)
  Iterative self-training with a quality gate. Each round:
    1. the CURRENT (improved) model re-transcribes the training clips,
    2. KEEP only pseudo-labels that pass a quality filter -- by default,
       agreement with the existing silver label (CER <= keep_cer); optionally an
       LLM judge,
    3. retrain on the cleaned/refined labels.
  Report dev/test WER/CER across rounds -- a downward curve is the contribution.
  The novel twist vs. plain self-training is the *quality-gated* refinement
  (agreement or LLM judge in the loop) under silver labels.

WHAT TO REPORT
  A "WER/CER vs. self-training round" curve, plus the final model vs. round-0.

USAGE
  python method2_self_training.py --rounds 2 \
      --out_prefix ../fine_tuning/models/ft_whisper_selftrain
  # start from an already fine-tuned checkpoint instead of round-0:
  python method2_self_training.py --rounds 2 \
      --init_model ../fine_tuning/models/ft_whisper_csaware \
      --out_prefix ../fine_tuning/models/ft_whisper_selftrain
  # smoke test:
  python method2_self_training.py --rounds 1 --max_train 60 --epochs 1 \
      --out_prefix ../fine_tuning/models/_smoketest_st

NOTE: at full scale this loads audio for transcription/retraining; use --max_train
to bound memory while validating, then scale up on the A100.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _common import (DEFAULT_DATASET, build_model_processor, finetune,  # noqa: E402
                     load_eval_split, load_split, prepare_for_training,
                     transcribe_clips)

try:
    from fine_tuning.config import BASE_MODEL
except Exception:
    BASE_MODEL = "openai/whisper-small"


def _cer(hyp: str, ref: str) -> float:
    import jiwer
    try:
        return jiwer.cer(ref or " ", hyp or " ")
    except Exception:
        return 1.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rounds", type=int, default=2)
    ap.add_argument("--out_prefix", required=True)
    ap.add_argument("--dataset", default=DEFAULT_DATASET)
    ap.add_argument("--base_model", default=BASE_MODEL)
    ap.add_argument("--init_model", default=None,
                    help="start from this checkpoint; else fine-tune a round-0 baseline first")
    ap.add_argument("--keep_cer", type=float, default=0.30,
                    help="keep a pseudo-label if CER(new, silver) <= this")
    ap.add_argument("--epochs", type=int, default=3)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--max_train", type=int, default=None)
    a = ap.parse_args()

    from datasets import Dataset, load_dataset

    # ---- current model: a fine-tuned checkpoint or a fresh round-0 baseline ----
    model, processor = build_model_processor(a.init_model or a.base_model)
    if a.init_model is None:
        print("[round 0] fine-tuning baseline on silver labels ...")
        tr = load_split(processor, a.dataset, "train", "all", a.max_train)
        ev = load_eval_split(processor, a.dataset, "all")
        finetune(model, processor, tr, ev, f"{a.out_prefix}_r0",
                 epochs=a.epochs, batch=a.batch)

    for r in range(1, a.rounds + 1):
        print(f"\n===== SELF-TRAINING ROUND {r} =====")
        raw = load_dataset(a.dataset, split="train")
        if a.max_train:
            raw = raw.select(range(min(a.max_train, len(raw))))

        # 1. re-transcribe with the current model
        print("  re-transcribing train clips ...")
        hyps = transcribe_clips(model, processor, raw, batch_size=a.batch)

        # 2. quality gate: keep clips whose new hyp agrees with the silver label
        keep_idx, keep_text = [], []
        for i, (ex, hyp) in enumerate(zip(raw, hyps)):
            if _cer(hyp, ex["sentence"]) <= a.keep_cer:
                keep_idx.append(i)
                keep_text.append(hyp)              # use the refined pseudo-label
        print(f"  kept {len(keep_idx)}/{len(raw)} pseudo-labels (CER <= {a.keep_cer})")
        if not keep_idx:
            print("  [warn] nothing kept -- relax --keep_cer; stopping.")
            break

        refined = raw.select(keep_idx)
        if "sentence" in refined.column_names:
            refined = refined.remove_columns("sentence")
        refined = refined.add_column("sentence", keep_text)

        # 3. retrain a fresh model on the refined labels
        print("  retraining on refined labels ...")
        model, processor = build_model_processor(a.base_model)
        train_ds = prepare_for_training(refined, processor)
        eval_ds = load_eval_split(processor, a.dataset, "all")
        out = f"{a.out_prefix}_r{r}"
        finetune(model, processor, train_ds, eval_ds, out,
                 epochs=a.epochs, batch=a.batch)
        print(f"  [round {r}] saved to {out}")

    print("[done] evaluate each round's model with evaluation/02_run_finetuned.py "
          "+ 03_compute_metrics.py and plot WER/CER vs. round.")


if __name__ == "__main__":
    main()
